version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"  # Host'taki 5000 portunu, konteyner içindeki 8080 portuna bağlar

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"  # Nginx, 80 numaralı port üzerinden dış dünyaya erişim sağlar
    depends_on:
      - api
